name: Housekeeping

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 

jobs:
  spellchecking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - uses: actions/setup-node@v1
        name: Run spell check
        with:
          node-version: "16"
      - run: npm install -g cspell
      - run: cspell --config ./cSpell.json "*.md"